sever:
  port: 8080
  error:
    include-message: on-param

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 644055749143-bs1eame2dme1otikcqcrq5jidhmauidt.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    mongodb:
      uri: mongodb+srv://dev_user:dev_user@voting-mdb-dev.xgjk9ie.mongodb.net/voting-mdb-dev